# Generated by Django 5.0.6 on 2024-06-13 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing_app', '0002_client_client_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='owned_by',
        ),
    ]
