# Generated by Django 5.0.6 on 2024-06-13 17:17

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing_app', '0003_remove_client_owned_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_country',
            field=django_countries.fields.CountryField(default='Kenya', max_length=2),
        ),
        migrations.AlterField(
            model_name='settings',
            name='company_country',
            field=django_countries.fields.CountryField(default='Kenya', max_length=2),
        ),
    ]
